<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Blog;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        Blog::create([
            'title' => 'Why I Started Working Out',
            'slug' => 'why-i-started-working-out',
            'category' => 'Lifestyle',
            'body' => '<p>Working out has become an integral part of my life, and I have come to realize the incredible benefits that come with it. In this blog, I will share my personal journey of why I started working out and how it has transformed my life.</p><p>Growing up, I was never interested in sports or physical activities. I spent most of my time indoors, reading books, and watching TV. As a result, I became overweight and lacked the energy and stamina to keep up with my peers. I was self-conscious about my body and struggled with low self-esteem.</p><img class="w-100 my-3" src="/asset/blogs/workout2.jpeg" alt=""><p>It wasn\'t until my mid-twenties that I realized I needed to make a change. I was tired of feeling lethargic and unhappy with my body, so I decided to start working out. At first, it was a struggle. I lacked the motivation and discipline to stick to a routine, and I felt uncomfortable in the gym.</p><p>However, over time, I began to see the benefits of working out. I started to feel more energetic and confident in my body. I also noticed improvements in my mental health, as exercise released endorphins that boosted my mood and reduced my stress levels.</p><p>Working out has also helped me develop a sense of discipline and self-control. It takes dedication and commitment to maintain a consistent workout routine, and this has translated to other areas of my life. I am more focused and productive at work, and I am better able to manage my time and prioritize my goals.</p><img class="w-100 my-3" src="/asset/blogs/workout3.jpeg" alt=""><p>One of the most significant benefits of working out, for me, has been the sense of community it provides. I joined a gym and started attending group fitness classes, which allowed me to meet new people and make friends. It\'s inspiring to be around others who share a common goal of living a healthy and active lifestyle.</p><p>In conclusion, starting to work out has been one of the best decisions I have made in my life. It has transformed me physically and mentally, providing me with the energy, confidence, and discipline to live a fulfilling life. If you\'re considering starting a workout routine, I encourage you to take the first step. It may be challenging at first, but the benefits are well worth it.</p>',
            'image' => 'workout.jpeg'
        ]);
        Blog::create([
            'title' => 'What I Love about Inception',
            'slug' => 'what-i-love-about-inception',
            'category' => 'Review',
            'body' => '<p>Inception is a 2010 science fiction action thriller film directed by Christopher Nolan and starring Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy, and Ken Watanabe. The movie is known for its mind-bending plot, stunning visual effects, and incredible performances. In this blog, I will share my review of Inception and why it is one of the greatest movies ever made.</p><p>The film is set in a world where technology exists to enter people\'s dreams and extract information from their subconscious. Leonardo DiCaprio plays the role of Dom Cobb, a skilled thief who is offered a chance to regain his old life in exchange for completing an impossible task of planting an idea in someone\'s mind through dream-sharing technology.</p><img class="w-100 my-3" src="/asset/blogs/inception2.jpeg" alt=""><p>One of the most impressive things about Inception is the complexity and depth of its plot. The film explores themes of reality, perception, and the nature of dreams. It is a movie that demands the viewer\'s full attention, and it rewards them with an incredible story that is both thought-provoking and emotionally engaging.</p><p>The performances in Inception are outstanding. Leonardo DiCaprio delivers a powerful performance as Cobb, a man struggling with his past and trying to make amends. The supporting cast is equally impressive, with Joseph Gordon-Levitt, Ellen Page, and Tom Hardy all delivering strong performances.</p><img class="w-100 my-3" src="/asset/blogs/inception3.jpeg" alt=""><p>The visual effects in Inception are breathtaking, and they are used to great effect in creating the dreamscapes that are the backdrop for the movie\'s action scenes. The cinematography is also exceptional, with the film\'s use of different locations and camera angles adding to the sense of disorientation and unreality that is central to the film\'s plot.</p><p>Inception is a movie that will leave you thinking long after the credits roll. It is a masterful work of storytelling and filmmaking that combines incredible performances, stunning visual effects, and a mind-bending plot. It is a movie that is not to be missed, and one that will be remembered as one of the greatest films ever made.</p><p>In conclusion, Inception is a masterpiece of cinema, a film that pushes the boundaries of storytelling and filmmaking. It is a must-see movie for anyone who loves great cinema, and it is a movie that will stay with you long after you\'ve watched it.</p>',
            'image' => 'inception.jpeg'
        ]);
        Blog::create([
            'title' => 'The World\'s Factory: Shenzhen',
            'slug' => 'the-world-factory-shenzhen',
            'category' => 'Travel',
            'body' => '<p>Shenzhen, located in the Guangdong Province of China, is a vibrant city that has transformed itself into a global hub of technology, manufacturing, and innovation. As someone who has had the opportunity to travel to Shenzhen, I can attest to the fact that it is a city that is definitely worth visiting. In this blog, I will share my experience of traveling to Shenzhen and what makes it such an exciting destination.</p><p>One of the things that struck me most about Shenzhen is its modernity. The city has developed rapidly over the past few decades, and it is now home to some of the most innovative technology companies in the world, such as Huawei, Tencent, and DJI. This has resulted in a skyline that is dotted with impressive skyscrapers and a public transportation system that is efficient and convenient.</p><p>Despite its modernity, Shenzhen is still deeply rooted in its culture and history. The city is home to a number of temples and historical sites, such as the Dapeng Fortress, which dates back to the Ming Dynasty. There are also several museums that showcase the city\'s rich cultural heritage, including the Shenzhen Museum and the Guan Shanyue Art Museum.</p><img class="w-100 my-3" src="/asset/blogs/shenzhen3.jpeg" alt=""><p>One of the highlights of my trip to Shenzhen was visiting the city\'s famous theme parks. Shenzhen has several world-class theme parks, including Window of the World, which features replicas of famous landmarks from around the world, and the Happy Valley amusement park, which has thrilling rides and attractions for visitors of all ages.</p><p>Another thing that makes Shenzhen an attractive destination is its proximity to Hong Kong. Shenzhen is located just across the border from Hong Kong, and it is easily accessible by train or bus. This makes it an ideal location for travelers who want to explore both cities during their trip.</p><img class="w-100 my-3" src="/asset/blogs/shenzhen2.jpeg" alt=""><p>Overall, my experience of traveling to Shenzhen was incredible. The city is a fascinating blend of modernity and tradition, and it offers visitors a unique glimpse into China\'s booming tech industry and rich cultural heritage. Whether you\'re interested in exploring historical sites, visiting theme parks, or experiencing the buzz of a modern metropolis, Shenzhen is definitely a destination worth considering.</p>',
            'image' => 'shenzhen.jpeg'
        ]);
        Blog::create([
            'title' => 'The Meaning Behind \'Wish You Were Gay\'',
            'slug' => 'the-meaning-behind-wish-you-were-gay',
            'category' => 'Review',
            'body' => '<p>Billie Eilish is undoubtedly one of the most talented and influential musicians of our time, and her hit song "wish you were gay" is a prime example of her skill as a songwriter and performer. With its haunting melody and poignant lyrics, "wish you were gay" is a beautifully crafted masterpiece that speaks to the heart of anyone who has experienced the pain of unrequited love.<p><img class="w-100 my-3" src="/asset/blogs/billie.jpeg" alt=""></p>From the opening notes of the song, it is clear that Billie Eilish has poured her heart and soul into this track. Her soulful vocals, combined with the minimalist instrumental backing, create an emotional intensity that is hard to ignore. The lyrics, which tell the story of a person who longs for the love of someone who does not reciprocate their feelings, are both heartbreaking and relatable.<p></p>But what really sets "wish you were gay" apart is its honesty and vulnerability. Billie Eilish has never been one to shy away from difficult topics, and in this song, she lays bare her deepest emotions and insecurities. By doing so, she invites her listeners to do the same, creating a sense of connection and empathy that is rare in modern music.<p><img class="w-100 my-3" src="/asset/blogs/billie3.jpeg" alt=""></p>Overall, "wish you were gay" is a masterpiece of songwriting and performance. It is a testament to Billie Eilish\'s talent and creativity, as well as her willingness to tackle difficult topics with honesty and vulnerability. If you haven\'t heard this song yet, I highly recommend giving it a listen. It is a powerful and moving piece of music that is sure to leave a lasting impression.</p>',
            'image' => 'billie2.jpeg'
        ]);
        Blog::create([
            'title' => 'Supreme Singapore',
            'slug' => 'supreme-singapore',
            'category' => 'Travel',
            'body' => '<p>Singapore is a vibrant and dynamic city-state located in Southeast Asia. Known for its beautiful architecture, rich cultural heritage, and impressive skyline, Singapore is a popular destination for tourists and business travelers alike. In this blog, we will explore some of the top attractions and experiences that this amazing city has to offer.</p><p>First on the list is the iconic Marina Bay Sands, a world-famous hotel and entertainment complex that dominates the city skyline. With its stunning infinity pool, rooftop bar, and breathtaking views of the city, Marina Bay Sands is a must-visit destination for anyone traveling to Singapore.</p><img class="w-100 my-3" src="/asset/blogs/singapore3.jpeg" alt=""><p>Another top attraction is the Gardens by the Bay, a nature park featuring beautiful gardens, towering trees, and a stunning conservatory filled with rare plants and flowers. Visitors can take a leisurely stroll through the gardens or enjoy a light show at the Supertree Grove, making it a perfect destination for nature lovers and families.</p><p>For a taste of Singaporean culture and history, be sure to visit the National Museum of Singapore, which showcases the city-state\'s rich past and cultural heritage through a variety of exhibits and interactive displays. The museum also hosts regular events and programs, making it a great destination for visitors of all ages.</p><img class="w-100 my-3" src="/asset/blogs/singapore2.jpeg" alt=""><p>Of course, no trip to Singapore would be complete without indulging in the city-state\'s amazing food scene. From hawker centers and street food stalls to Michelin-starred restaurants and fine dining establishments, Singapore is a food lover\'s paradise. Be sure to try local favorites like chicken rice, laksa, and char kway teow, and don\'t forget to sample some of the amazing desserts and sweets that Singapore is famous for.</p><p>Whether you\'re interested in history, nature, food, or simply soaking up the city\'s unique culture and vibe, Singapore has something for everyone. With its beautiful sights, amazing food, and warm and welcoming people, it\'s no wonder that this city-state is a top destination for travelers from around the world.</p>',
            'image' => 'singapore.jpeg'
        ]);
        Blog::create([
            'title' => 'How Long Should We Sleep?',
            'slug' => 'how-long-should-we-sleep',
            'category' => 'Lifestyle',
            'body' => '<p>Sleep is an essential aspect of maintaining good health and overall well-being. It allows our bodies and minds to rest and recharge, enabling us to perform at our best throughout the day. But how much sleep do we actually need? In this blog, we\'ll explore the recommended hours of sleep for different age groups and the benefits of getting enough rest.</p><p>According to the National Sleep Foundation, adults between the ages of 18 and 64 should aim to get 7-9 hours of sleep per night. For older adults aged 65 and above, the recommended range is 7-8 hours per night. These guidelines are based on extensive research and take into account individual differences in sleep needs.</p><img class="w-100 my-3" src="/asset/blogs/sleep2.jpg" alt=""><p>Getting enough sleep has numerous benefits for our physical and mental health. It can help improve memory, mood, and concentration, reduce the risk of developing chronic diseases such as diabetes and heart disease, and enhance athletic performance and overall productivity.</p><p>On the other hand, not getting enough sleep can have serious negative consequences. Chronic sleep deprivation can lead to a weakened immune system, increased stress levels, and decreased cognitive function. It can also increase the risk of accidents, both on the road and in the workplace.</p><p>While the recommended hours of sleep may vary depending on age and individual needs, it is important to prioritize rest and ensure that we are getting enough sleep to support our health and well-being. Establishing a consistent sleep schedule, creating a relaxing sleep environment, and practicing good sleep hygiene can all help improve the quality and quantity of our sleep.</p><img class="w-100 my-3" src="/asset/blogs/sleep3.jpg" alt=""><p>In conclusion, getting enough sleep is crucial for maintaining good health and well-being. By prioritizing rest and striving to get the recommended hours of sleep each night, we can improve our physical and mental health, enhance our productivity and performance, and enjoy a happier, healthier life.</p>',
            'image' => 'sleep.jpeg'
        ]);
        Blog::create([
            'title' => 'The Power of Eating Healthy',
            'slug' => 'the-power-of-eating-healthy',
            'category' => 'Lifestyle',
            'body' => '<p>Eating a healthy diet is one of the most important things we can do to support our overall health and well-being. A nutritious diet can help reduce the risk of chronic diseases, improve energy levels, boost mood, and support healthy weight management. In this blog, we\'ll explore the benefits of eating healthy and provide tips for incorporating more nutritious foods into your diet.</p><p>One of the key benefits of eating healthy is the ability to reduce the risk of chronic diseases such as heart disease, diabetes, and certain types of cancer. A healthy diet is rich in fruits, vegetables, whole grains, lean proteins, and healthy fats, which provide the nutrients and antioxidants our bodies need to function at their best.</p><img class="w-100 my-3" src="/asset/blogs/food2.png" alt=""><p>In addition to reducing the risk of chronic diseases, eating a nutritious diet can also improve energy levels, boost mood, and support healthy weight management. Nutritious foods provide the fuel our bodies need to function optimally, while also providing the nutrients that support our physical and mental health.</p><p>So, how can you incorporate more healthy foods into your diet? One approach is to focus on whole, minimally processed foods. This includes fresh fruits and vegetables, whole grains, lean proteins such as chicken, fish, and beans, and healthy fats such as avocados, nuts, and olive oil.</p><p>Another strategy is to reduce your intake of processed and refined foods, such as sugary drinks, processed meats, and white bread. These foods are often high in calories and low in nutrients, making them a poor choice for overall health and wellness.</p><img class="w-100 my-3" src="/asset/blogs/food3.jpeg" alt=""><p>Finally, it\'s important to make healthy eating a sustainable habit by focusing on balance and moderation. This means enjoying a variety of nutritious foods in appropriate portions, and allowing for occasional indulgences and treats.</p><p>In conclusion, eating a healthy diet is essential for supporting overall health and well-being. By focusing on whole, minimally processed foods, reducing intake of processed and refined foods, and practicing balance and moderation, we can improve our physical and mental health, boost energy levels, and enjoy a happier, healthier life.</p>',
            'image' => 'food.jpeg'
        ]);
        Blog::create([
            'title' => 'My All Time Favorite Superhero Movie',
            'slug' => 'my-all-time-favorite-superhero-movie',
            'category' => 'Review',
            'body' => '<p>"The Dark Knight" is a film that has captivated audiences since its release in 2008. Directed by Christopher Nolan and starring Christian Bale as Batman and the late Heath Ledger as the Joker, the film is widely regarded as a masterpiece of the superhero genre.</p><p>The film\'s success is due in part to its gritty, realistic approach to the Batman universe. Nolan eschewed the fantastical elements of previous Batman films in favor of a darker, more grounded tone. This allowed the film to explore complex themes and issues in a way that felt relevant and thought-provoking.</p><img class="w-100 my-3" src="/asset/blogs/batman2.jpeg" alt=""><p>One of the central themes of "The Dark Knight" is the nature of heroism. Batman is forced to confront his own limitations as a hero, as he struggles to balance his desire to protect Gotham City with the constraints of the law and the dangers posed by the Joker. The film also delves into issues of morality and justice, as Batman and his allies are forced to make difficult decisions in their fight against the Joker and his followers.</p><img class="w-100 my-3" src="/asset/blogs/batman3.jpg" alt=""><p>Perhaps the most memorable aspect of "The Dark Knight" is Ledger\'s stunning portrayal of the Joker. His performance is chilling and captivating, and he imbues the character with a sense of chaotic malevolence that is both terrifying and mesmerizing. Ledger\'s tragic death shortly after the film\'s release only adds to the aura of mystique surrounding his performance.</p><p>Overall, "The Dark Knight" is a masterful film that transcends the superhero genre. Its complex themes, stunning visuals, and unforgettable performances have cemented its place in cinematic history, and it continues to be celebrated and studied by fans and critics alike.</p>',
            'image' => 'batman.jpg'
        ]);
        Blog::create([
            'title' => 'Exploring the Wonders of ChatGPT',
            'slug' => 'exploring-the-wonders-of-chatgpt',
            'category' => 'Review',
            'body' => '<p>As an AI language model, ChatGPT has quickly become a valuable resource for people all over the world. Whether you\'re looking for information on a particular topic, or just want to engage in conversation, ChatGPT is always ready to assist you.</p><p>One of the things that sets ChatGPT apart from other AI language models is its ability to understand and respond to natural language. This means that you can ask ChatGPT a question or make a statement in the same way that you would speak to a human being, and it will be able to understand and provide a relevant response.</p><p>Another impressive feature of ChatGPT is its vast knowledge base. It has been trained on a massive dataset of text, allowing it to provide detailed and accurate information on a wide range of topics. Whether you\'re interested in science, history, literature, or current events, ChatGPT has you covered.</p><img class="w-100 my-3" src="/asset/blogs/chatgpt2.jpg" alt=""><p>ChatGPT is also highly customizable, with the ability to learn from user input and adapt to individual preferences. For example, if you consistently ask ChatGPT questions about a particular topic, it will start to tailor its responses to that area of interest.</p><p>Overall, ChatGPT is an incredibly useful tool for anyone looking to learn, engage in conversation, or simply have some fun. Its natural language processing abilities, vast knowledge base, and adaptability make it a valuable resource for people of all ages and backgrounds. If you haven\'t already tried ChatGPT, it\'s definitely worth giving it a go!</p>',
            'image' => 'chatgpt.jpg'
        ]);
        Blog::create([
            'title' => 'A Journey through Nature, Culture, and Cuisine',
            'slug' => 'a-journey-through-nature-culture-and-cuisine',
            'category' => 'Travel',
            'body' => '<p>Travelling to Qinghai is a unique and rewarding experience that offers a glimpse into the rich cultural and natural heritage of this province in northwest China. Whether you are a nature lover, a history buff, or a foodie, Qinghai has something for everyone.</p><p>One of the highlights of visiting Qinghai is its stunning scenery. The province is home to some of the most breathtaking landscapes in China, including vast grasslands, snow-capped mountains, and crystal-clear lakes. One of the must-visit attractions is Qinghai Lake, which is the largest saltwater lake in China and is surrounded by towering mountains. Another popular destination is Kumbum Monastery, which is a sacred Tibetan Buddhist site and is known for its intricate architecture and stunning mountain views.</p><img class="w-100 my-3" src="/asset/blogs/qinghai3.jpeg" alt=""><p>In addition to its natural beauty, Qinghai is also known for its delicious cuisine. The province has a rich culinary tradition, with many dishes featuring locally sourced ingredients like yak meat, wild herbs, and barley. One of the most famous dishes is "Qinghai Plateau Yak Meat," which is a savory and hearty dish that is often served with noodles or rice. Another popular dish is "Liangfen," which is a cold dish made from mung bean jelly and is typically served with a spicy sauce.</p><img class="w-100 my-3" src="/asset/blogs/qinghai2.jpg" alt=""><p>Aside from its natural beauty and delicious cuisine, Qinghai is also home to a number of cultural attractions that are worth exploring. One such attraction is Ta\'er Monastery, which is one of the most important Tibetan Buddhist monasteries in China and is known for its intricate carvings and colorful murals.</p><p>Overall, a trip to Qinghai is a wonderful way to experience the natural beauty, rich culture, and delicious cuisine of this unique province in China. Whether you are looking to explore the stunning scenery, taste the local cuisine, or immerse yourself in the region\'s history and culture, Qinghai is sure to leave a lasting impression on you.</p>',
            'image' => 'qinghai.jpg'
        ]);
        Blog::create([
            'title' => 'Unveiling the Charms of the Cat City',
            'slug' => 'unveiling-the-charms-of-the-cat-city',
            'category' => 'Travel',
            'body' => '<p>If you\'re looking for a unique and memorable travel experience, consider a trip to Kuching, the vibrant capital city of Sarawak in Malaysia. With its rich cultural heritage, delicious cuisine, and stunning natural beauty, Kuching is a destination that has something for everyone.</p><img class="w-100 my-3" src="/asset/blogs/kuching2.jpeg" alt=""><p>One of the highlights of visiting Kuching is exploring the city\'s rich cultural heritage. The city is home to a number of museums, including the Sarawak Museum, which showcases the history and culture of the state. Other must-visit cultural attractions include the Kuching Waterfront, which is a bustling area along the Sarawak River that is lined with shops, restaurants, and historical buildings. You can also visit the Sarawak Cultural Village, which is a living museum that showcases the traditional customs and lifestyles of the different ethnic groups in Sarawak.</p><p>Another great reason to visit Kuching is its unique cuisine. The city is known for its delicious street food, which features a blend of Malay, Chinese, and Indian flavors. Some of the must-try dishes include Sarawak laksa, which is a spicy noodle soup, and kolo mee, which is a type of noodle dish that is usually served with barbecued meat. You can also try local fruits like durian and rambutan, which are popular throughout Malaysia.</p><img class="w-100 my-3" src="/asset/blogs/kuching3.jpeg" alt=""><p>Beyond the city, Kuching is surrounded by stunning natural beauty. One of the top attractions is the Bako National Park, which is located on the coast and is home to a diverse range of flora and fauna. You can also take a boat ride along the Sarawak River to see the city from a different perspective, or visit nearby Semenggoh Nature Reserve to see orangutans in their natural habitat.</p><p>Overall, a trip to Kuching is a fantastic way to experience the rich culture, delicious cuisine, and stunning natural beauty of Sarawak in Malaysia. Whether you\'re looking to explore the city\'s history and culture, taste its unique cuisine, or immerse yourself in its natural wonders, Kuching is sure to leave a lasting impression on you.</p><p>So why not pack your bags and start planning your next adventure to Kuching? You won\'t regret it!</p>',
            'image' => 'kuching.jpeg'
        ]);


    }
}
